### ISSUE TITLE
Fix Translation Dropdown

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#74]
The dropdown menu is hidden right now.

![Image](https://github.com/jadeallencook/communalists/assets/4443883/7869aeb6-e029-40ff-94ef-e39e3025f0e8)

Acceptance Criteria:
- Clicking on the language should display the dropdown menu
- There should be no x-axis scrolling
- Mobile menu should still function properly
- Choosing new language should close menu

**Comment by asbhaskar** [comment]
Please confirm if this is still broken in the latest Vercel `Preview` deployment, https://communalists-ffogs99a1-jadeallencook.vercel.app/ and if so, which browser

**Comment by jadeallencook** [comment]
Are you able to reproduce this issue @A1Liu ? 

I'm using Safari @asbhaskar and I'm not seeing it.

Maybe it's a browser specific bug.

**Comment by A1Liu** [comment]
@jadeallencook this should be fixed as of #67 , I will close it and if it comes up again we can reopen.
