### ISSUE TITLE
View Coordinator/Driver

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#75]
Clicking on the "view" button next to the driver or coordinator should display their name.

![Image](https://github.com/jadeallencook/communalists/assets/4443883/2f5ec6f0-78c4-470c-bd37-601855977e97)

Acceptance Criteria:
- View button should be disabled if there is no volunteer
- Should use the dashboard context to check cache first
- If user is in cache, then disable view button and display name
- If user is not in cache, we should fetch user and cache

**Comment by A1Liu** [comment]
Putting this on hold until users' names are in a single doc

**Comment by jadeallencook** [comment]
I've gone ahead and created a new issue to resolve this:
https://github.com/jadeallencook/communalists/issues/84
