### ISSUE TITLE
Design Simple Homepage

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#82]

**Comment by jadeallencook** [comment]
I'd like to design a simple homepage for the site, so it doesn't just show the request forum when someone loads the site. We're getting quite a bit of traffic from Google since we're at the top of the search results for "communalists". Here's some of the ideas I'm thinking:

- Header with a call to action
- Links to information
- Spotlight for organizations we work with
- Answers to frequently asked questions
- Links to volunteer forums on other sites

This is still all up in the air, let me know your thoughts.

**Comment by asbhaskar** [comment]
This is a cool idea, maybe we could add a brief paragraph below the fold on what communalists is/does. The wording depends a lot on who we're targeting with this homepage. At this stage when we're looking at recruiting orgs, I'd suggest talking about how we're a collaboration tool for orgs.  

It'd also be cool if we could add some mutual aid info in the faq, maybe condense sbma's "What is mutual aid page", links for info could also go here. Spotlighting and links to volunteer forums could also be once section - maybe we have a "spotlight of the month" with an org logo, org submitted description/summary of work, link to homepage.
