### ISSUE TITLE
Create Username Collection

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#84]
Right now we're hiding usernames until someone reveals it to reduce the amount of reads. This is because usernames are stored in accounts, and we need to retrieve each account document to get the username. To make it so we can display usernames and reduce the amount of reads, we would like to add a usernames collection that looks like this:

```js
{
    "user-1": "John Doe",
    "user-2": "Jane Doe",
}
```

We will grab this entire collection after a user logs into the dashboard. This will work for now, since we have less than a hundred users, but we will eventually need to think of a better solution.

Acceptance Criteria: 
- There is a username collection in the database
- The keys are UIDs and the values are the usernames
- Updating your name in settings updates the database
- Fetch all usernames and cache them when user logs into dashboard
- Remove any references to the old usernames in accounts
- Remove the UI to reveal usernames since they will be displayed automatically
- If an account does not have a username, display "Anonymous"

**Comment by A1Liu** [comment]
It might be possible to get caching through Vercel for free using https://vercel.com/docs/concepts/edge-network/caching
