### ISSUE TITLE
Handle Frontend Errors

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#85]
We are currently handling frontend errors differently depending on the part of the application. I'd like to display a toast at the bottom center of the screen to display all errors/success messages. 

Acceptance Criteria:
- There is a notifications context the wraps the entire application
- The context returns an "addNotification" method
- The add notification method utilizes this interface:
```ts
interface Notification {
    message: string;
    isError?: boolean;
}
```
- Notifications stack on the bottom of the screen
- A notification is shown for a total of 5 seconds 
- There is a countdown that says "Closing in x seconds"
- User is able to close notification using "x" button 
- Default uses "light" and errors use "danger"
- Header for error reads "Error Notification"
- Default header reads "Notification"
- This is implemented on login page for if user enters wrong password
- Any copy is added to a snippet

**Comment by A1Liu** [comment]
@jadeallencook I'm prettier sure this is done now right? Do you feel there's anything missing that needs to be added before this can be closed?

**Comment by A1Liu** [comment]
Just gonna close it, can always reopen
