### ISSUE TITLE
Remove Member Functionality

### ISSUE THREAD

**Issue by jadeallencook** [jadeallencook/communalists#92]
Acceptance Criteria:
- Moderators should be able to remove a member from the organization
- Show a remove button to the right of the user's name
- Clicking button should split the button prompt user with a "are you sure" message
- There should be a yes and no buttons to the right of the "are you sure" message
- Message and buttons should be within a form group 

![Image](https://user-images.githubusercontent.com/4443883/242165017-7a3a8aba-f8bc-4c60-9901-afe306ef52eb.png)

**Comment by asbhaskar** [comment]
What if we turned the list of users into a table with check boxes on the left column and put the buttons separately on the top right above the table? This would allow us to easily add a filter to the table and clear up some space for future features (skills, etc...)

**Comment by jadeallencook** [comment]
Great idea @asbhaskar!
